name: budget_planner_app
description: A budget planner app with tracking features
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2
  provider: ^6.1.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/spending-money.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/spending-money.png"
flutter:
  assets:
    - assets/fonts/
    - assets/images/
  uses-material-design: true
